### ISSUE TITLE
Settings are saved and loaded from 2 different locations

### ISSUE THREAD

**Issue by Splintertx** [mipen/ModLib#5] opened 2020-04-15 00:19 UTC
Saved settings are loaded from a different location they are saved. It is impossible to load non-default settings.

**Comment by Splintertx** [comment] 2020-04-15 00:54
#6 also appears to resolve this

**Comment by mipen** [comment] 2020-04-15 04:23
Thanks for the heads up, looks like the issue is fixed now.

**Closed as completed by mipen** 2020-04-15 04:23 UTC
